RETINUE_VIRTUALENVWRAPPER_PATH = None
RETINUE_WORKON_HOME = None
RETINUE_PROJECTS_HOME = None
RETINUE_SVN_BASE_PATH = None
RETINUE_SVN_USERNAME = None
RETINUE_SVN_PASSWORD = None
RETINUE_HOME = None

RETINUE_NGINX_PATH = None
RETINUE_NGINX_CONF = None
RETINUE_NGINX_UPSTREAM_HOME = None
