RETINUE_VIRTUALENVWRAPPER_PATH = None
RETINUE_WORKON_HOME = None
RETINUE_APP_HOME = None
RETINUE_VASSAL_HOME = None
RETINUE_HOME = None

RETINUE_NGINX_PATH = None
RETINUE_NGINX_CONF = None
RETINUE_NGINX_UPSTREAM_HOME = None

EMPRESS_SERVICE_URL = None
